/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DelfinenPart1.presentation;

import DelfinenPart1.data.DBConnector;
import DelfinenPart1.data.DataAccessorDB;
import delfinendel1.logic.Controller;
import delfinendel1.logic.competitiveMember;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William Huusfeldt, Asger H. Sørensen.
 */
public class GUI_ShowCompetitiveMembers extends javax.swing.JFrame {

    /**
     * Creates new form GUI_ShowCompetitiveMembers
     */
    DataAccessorDB da = null;
    GUI_MainMenu guimm = null;
    Controller c = new Controller();
    DBConnector connector = null;

    public GUI_ShowCompetitiveMembers() {
        initComponents();
        try {
            da = new DataAccessorDB(new DBConnector());
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Setup fail!");
        }
        addTojFrame();
        this.getContentPane().setBackground(Color.WHITE);
        this.jTable1_showCM.setBackground(Color.WHITE);
        this.BackCrawl.setBackground(Color.WHITE);
        this.Breaststroke.setBackground(Color.WHITE);
        this.Crawl.setBackground(Color.WHITE);
        this.IDGoesHere.setBackground(Color.WHITE);
        this.Butterfly.setBackground(Color.WHITE);
        this.jButton1.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_showCM = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BackCrawl = new javax.swing.JButton();
        Breaststroke = new javax.swing.JButton();
        Crawl = new javax.swing.JButton();
        Butterfly = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        IDGoesHere = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1_showCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fornavn", "Efternavn", "Alder", "Hold", "Køn", "Butterfly", "Crawl", "Backcrawl", "Breaststroke"
            }
        ));
        jScrollPane1.setViewportView(jTable1_showCM);

        jButton1.setText("Tilbage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BackCrawl.setText("Sæt rygcrawl tid");
        BackCrawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackCrawlActionPerformed(evt);
            }
        });

        Breaststroke.setText("Sæt bryst tid");
        Breaststroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreaststrokeActionPerformed(evt);
            }
        });

        Crawl.setText("Sæt crawl tid");
        Crawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrawlActionPerformed(evt);
            }
        });

        Butterfly.setText("Sæt butterfly tid");
        Butterfly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButterflyActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        IDGoesHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDGoesHereActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Tid:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Butterfly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Crawl)
                        .addGap(3, 3, 3)
                        .addComponent(BackCrawl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Breaststroke))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Butterfly)
                    .addComponent(Crawl)
                    .addComponent(BackCrawl)
                    .addComponent(Breaststroke)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackCrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCrawlActionPerformed
        c.insertBCTime(Integer.parseInt(IDGoesHere.getText()), Double.parseDouble(jTextField1.getText()));
        addTojFrame();
    }//GEN-LAST:event_BackCrawlActionPerformed

    private void CrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrawlActionPerformed
        c.insertCTime(Integer.parseInt(IDGoesHere.getText()), Double.parseDouble(jTextField1.getText()));
        addTojFrame();
    }//GEN-LAST:event_CrawlActionPerformed

    private void ButterflyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButterflyActionPerformed
        // Butterfly tid
        c.insertBTime(Integer.parseInt(IDGoesHere.getText()), Double.parseDouble(jTextField1.getText()));
        addTojFrame();
    }//GEN-LAST:event_ButterflyActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // indtast tid
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void IDGoesHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDGoesHereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDGoesHereActionPerformed

    private void BreaststrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreaststrokeActionPerformed
        c.insertBSTime(Integer.parseInt(IDGoesHere.getText()), Double.parseDouble(jTextField1.getText()));
        addTojFrame();
    }//GEN-LAST:event_BreaststrokeActionPerformed

    public void addTojFrame() {

        List<competitiveMember> competitiveMembers = da.getCompetitiveMembers();
        DefaultTableModel model = (DefaultTableModel) jTable1_showCM.getModel();
        model.setRowCount(0);
        for (competitiveMember cm : competitiveMembers) {
            model.addRow(new Object[]{cm.getID(), cm.getFname(), cm.getLname(), cm.getAge(), cm.getTeam(), cm.getSex(), cm.getBtime(), cm.getCtime(), cm.getBctime(), cm.getBstime()});
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowCompetitiveMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowCompetitiveMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowCompetitiveMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ShowCompetitiveMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ShowCompetitiveMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackCrawl;
    private javax.swing.JButton Breaststroke;
    private javax.swing.JButton Butterfly;
    private javax.swing.JButton Crawl;
    private javax.swing.JTextField IDGoesHere;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_showCM;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
